---
title: "Figure"
author: "Phuong Huynh Thi"
date: "19/10/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
#loading packages
library(grid)
library(gridExtra)
library(base)
library(dplyr)
library(tidyr)
library(rstan)
library(DescTools)
library(data.table)

```

# Data input
```{r data input, echo=FALSE}
dataInput <-"C1D1" # C1D1, C1F1, C1D3, C1F3
groupAge <- 5 #1,5 # Grouping Input data by group of ....
##Results from immune status (model C) and infecting serotype infering models ( model D vs Model F:
#Model C1D1
df1 <- read.csv("./data/PredictedIS_B23_567_pred.serotype_C1D1.csv")
df1$sero.model <- "CD"
#Model C1F1
df2 <- read.csv("./data/PredictedIS_B23_567_pred.serotype_HomoAssigned_C1F1.csv")
df2$sero.model <- "CF"
data <- rbind(df1,df2)

data$YEAR <- as.factor(data$YEAR)
data$predictedIS<- ordered(data$predictedIS,levels=c("Secondary","Primary","Neg"))

data$pred.serotype<- as.factor(data$pred.serotype)
levels(data$pred.serotype) <- c("DENV1","DENV2", "DENV3","DENV4","Negative","Secondary")
data$pred.serotype <- ordered(data$pred.serotype,levels=c("Secondary","DENV4","DENV3","DENV2","DENV1","Negative"))


pop<- data[which(!is.na(data$AGE_MIN)&is.na(data$PanbioUnit)),]# cross out acute and ELISA samples
pop$Site <- substr(pop$sampleID,1,2)

# Age stratification
if(groupAge == 1){
  ##Agegroup_ 1year
  pop$AgeGroup <-factor(as.factor(ceiling(pop$AGE_MIN)),labels=c("(1-2]","(2-3]","(3-4]","(4-5]","(5-6]","(6-7]","(7-8]","(8-9]","(9-10]","(10-11]","(11-12]","(12-13]","(13-14]","(14-15]","(15-16]","(16-17]","(17-18]","(18-19]","(19-20]","(20-21]","(21-22]","(22-23]","(23-24]","(24-25]","(25-26]","(26-27]","(27-28]","(28-29]","(29-30]"))# group as  1year 1 group, no individual is less than 1 year old
pop$AgeGroup1 <-factor(as.factor(ceiling(pop$AGE_MIN)),labels=c("1-2","2-3","3-4","4-5","5-6","6-7","7-8","8-9","9-10","10-11","11-12","12-13","13-14","14-15","15-16","16-17","17-18","18-19","19-20","20-21","21-22","22-23","23-24","24-25","25-26","26-27","27-28","28-29","29-30"))
}
if(groupAge == 2){
  pop$AgeGroup <-factor(as.factor(ceiling(pop$AGE_MIN/2)),labels=c("(0-2]","(2-4]","(4-6]","(6-8]","(8-10]","(10-12]","(12-14]","(14-16]","(16-18]","(18-20]","(20-22]","(22-24]","(24-26]","(26-28]","(28-30]"))
}
if(groupAge == 3){
  pop$AgeGroup <- ceiling(pop$AGE_MIN/3)
  pop$AgeGroup <- factor(
    pop$AgeGroup,
    labels = c("(0-3]","(3-6]","(6-9]","(9-12]","(12-15]","(15-18]",
               "(18-21]","(21-24]","(24-27]","(27-30]"))
}
if(groupAge == 5){
  pop$AgeGroup <- ceiling(pop$AGE_MIN/5)
  pop$AgeGroup <- factor(
    pop$AgeGroup,
    labels = c("(0-5]","(5-10]","(10-15]","(15-20]","(20-25]","(25-30]"))
}

```

# Figure2 (model CD)

```{r serotypes by years ,message=FALSE, echo=FALSE,message=FALSE,fig.height=4,fig.width=12}

# dplyr cheatsheet to summary data
if( dataInput=="C1D1"){
  d=dplyr::filter(pop,sero.model=="CD")%>%group_by(AgeGroup,Site,YEAR,sero.model,pred.serotype )%>% dplyr::count(AgeGroup)
}
if( dataInput=="C1F1"){
  d=dplyr::filter(pop,sero.model=="CF")%>%group_by(AgeGroup,Site,YEAR,sero.model,pred.serotype )%>% dplyr::count(AgeGroup)
}

#New facet label name for site variable
site.labs <- c("Ho Chi Minh","Khanh Hoa")# new name
names(site.labs) <- c("HC", "KH")# old name

ser<- ggplot(d,aes(x=YEAR,y=n,fill=pred.serotype))+
  geom_bar(position="fill",stat="identity")+
  geom_bar(position="fill",stat="identity")+
  scale_fill_manual(values=c("#67a9cf","chocolate3","burlywood3","cornsilk4","azure3","light blue"))+
  # ggtitle("KH")+
  labs(y="Proportion", x="Year")+
  theme( plot.title = element_text(size=20,hjust = 0.5),
         strip.text.x = element_text(size=15),
         axis.title = element_text(size = 12,face="bold"),
         axis.text = element_text(face="bold", size = 12),
          legend.text = element_text(size = 12 ),
         legend.title = element_blank())+
  facet_grid(~Site, labeller = labeller(Site=site.labs))
# legend.position = "none")+
ser
# Manual save figure 1000x 500 or
ggsave(filename=paste("./output/figures/Fig2.png"), plot = ser, height = 8, width = 12)
```
