---
title: "Lambda extraction from fit object"
author: "Phuong Huynh Thi"
date: "27/10/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())

library(StanHeaders)
library(rstan)
library(readr)
library(loo)
library(ggplot2)
library(dplyr)
library(ggpubr)#ggarrange

```

#FOI estimated by each model
## recall saved data
```{r fig.height=10,fig.width=10}
# changeable variables
# model <- "cons" # cons, TV,SS, TVSS
dataInput <- "CD" #CD, CF
groupAge <- 5 #1,5
stat <- "quantile" # CI, quantile( 1st to 3rd)

# combine all files
#summary of lambda
df_sum <- list.files(path="./output/statistics/summary", full.names = TRUE)%>% 
  lapply(read_csv)%>% 
   bind_rows

# write.csv(df_sum,"./output/statistics/summary FoI_allModels&Site.csv")
# Model C1D1 and C1F1 
df_sum<- dplyr::filter(df_sum, dataInput=="C1D1"|dataInput=="C1F1")
#replace dataInput name
df_sum$dataInput[df_sum$dataInput=="C1D1"] <- "CD"
df_sum$dataInput[df_sum$dataInput=="C1F1"] <- "CF"

# adding standard error for later ploting
df_sum$error <- df_sum$Mean-df_sum$lwr.ci
df_sum$dis.1stQu <- df_sum$Median - df_sum$`1st Qu.` # distance from median to 1stQu.
df_sum$dis.3rdQu <- df_sum$`3rd Qu.`- df_sum$Median  # distance from median to 1stQu.
# write.csv(df_sum,"./output/statistics/summary_all.csv")
df_sum$site <- as.factor(df_sum$site)
df_sum$serotype <- as.factor(df_sum$serotype)

if(groupAge ==1){
  df_sum<- df_sum%>%dplyr::filter(groupAge == 1)
}
if(groupAge == 5){
  df_sum<- df_sum%>%dplyr::filter(groupAge == 5)
}

```

## cons
```{r fig.height=10,fig.width=10}
# changeable variables
model <- "cons" # cons, TV,SS, TVSS
#cons model
if(model == "cons"){
  df<- dplyr::filter(df_sum, model=="cons",dataInput=="CD")
  p1 <- ggplot(df,aes(x= dataInput, y= Median, color=site))+
    scale_color_manual(values=c("#c51b8a","#3182bd"))+
    geom_errorbar(aes(ymin = Median - dis.1stQu,
                      ymax = Median + dis.3rdQu,
                      width = 0.1))+
    labs(y="Estimated force of infection", x="")+
    ggtitle("Model 1")+
    geom_point()+
    ylim(0,0.1)+
    # facet_grid(~site)+
    theme_bw()+   # change the background
    theme(plot.title = element_text(size=14,face = "bold",hjust=0),
          axis.text.x = element_blank())
    # ggtitle(paste("Estimated lambda_",model)) 
  p1
}

```

## SS
```{r fig.height=10,fig.width=10}
# changeable variables
model <- "SS" # cons, TV,SS, TVSS

#SS model
if(model == "SS"){
df<- dplyr::filter(df_sum, model=="SS", dataInput=="CD")
 p2 <- ggplot(df,aes(x= dataInput, y= Median, color=serotype))+
    scale_color_manual(values=c("#f16913","#bf812d","#7fbc41","#7bccc4"))+
  geom_errorbar(aes(ymin = Median - dis.1stQu,
                      ymax = Median + dis.3rdQu,
                      width = 0.1))+
  labs(y="Estimated force of infection")+
   ggtitle("Model 2")+
  geom_point()+
   ylim(0,0.1)+
  facet_grid(site~.)+
   theme_bw()+   # change the background
  theme(plot.title = element_text(size=14,face = "bold",hjust=0),
        axis.text.x = element_blank(),
        axis.title.x = element_blank())
  # ggtitle(paste("Estimated lambda_",model)) #"#d73027"
p2
}



```

## TV
```{r fig.height=10,fig.width=10}
# changeable variables
model <- "TV" # cons, TV,SS, TVSS

#TV model
if(model=="TV"&dataInput == "CD"){#
  df<- dplyr::filter(df_sum, model=="TV")
  df$year.lamb <- 2017 - df$year.lamb +1
  #eliminating the last 5yrs???? 1983-1986 
  df<-df%>%filter(dataInput=="CD")#&year.lamb>=1987
}
if(dataInput == "CF"){
  df<- dplyr::filter(df_sum, model=="TV")
  df$year.lamb <- 2017 - df$year.lamb +1
  df<-df%>%filter(dataInput=="CF")#&year.lamb>=1987
}

df$dataInput <- as.factor(df$dataInput)
if(model=="TV"){
  p3 <- ggplot(df,aes(x=year.lamb,y= Median, color=site))+
    geom_point()+
    scale_color_manual(values=c("#c51b8a","#3182bd"))+
    geom_errorbar(aes(ymin = Median - dis.1stQu,
                      ymax = Median + dis.3rdQu,
                      width = 0.1))+
    labs(y="Estimated force of infection", x = "time (years)")+
    ggtitle("Model 3")+
    ylim(0,0.1)+
    theme_bw()+   # change the background
    theme(axis.text.x = element_text(angle = 90),
          # axis.title.x = element_blank(),
          plot.title = element_text(size=14, face="bold",hjust=0))+
    scale_x_continuous(breaks = seq(1983,2017,by=2))
    # facet_grid(dataInput~.)
    # ggtitle(paste("Estimated lambda_",model,dataInput)) 
  p3
}

```

## TVSS
```{r fig.height=10,fig.width=10}
# changeable variables
model <- "TVSS" # cons, TV,SS, TVSS

#TVSS model
if(model=="TVSS"&dataInput == "CD"){
  df<- dplyr::filter(df_sum, model=="TVSS")
  df$year.lamb <- 2017 - df$year.lamb +1
  #eliminating the last 5yrs???? 1983-1986 
  df<-df%>%filter(dataInput=="CD")#&year.lamb>=1987
}
if(dataInput == "CF"){
  df<- dplyr::filter(df_sum, model=="TVSS")
  df$year.lamb <- 2017 - df$year.lamb +1
  df<-df%>%filter(dataInput=="CF")#&year.lamb>=1987
}

if(model=="TVSS"){
  p4 <- ggplot(df,aes(x=year.lamb,y= Median, color=serotype))+
    geom_point()+
    scale_color_manual(values=c("#f16913","#bf812d","#7fbc41","#7bccc4"))+
     geom_errorbar(aes(ymin = Median - dis.1stQu,
                      ymax = Median + dis.3rdQu,
                      width = 0.1))+
    labs(y="Estimated force of infection", x = "time (years)")+
    ggtitle("Model 4")+
    ylim(0,0.1)+
    theme_bw()+   # change the background
    theme(axis.text.x = element_text(angle = 90, size=7, face = "bold"),
          # axis.title.x = element_blank(),
          plot.title = element_text(size=14, face="bold",hjust=0))+
    scale_x_continuous(breaks = seq(1983,2017,by=2))+
    facet_grid(site~.)
    # ggtitle(paste("Estimated lambda_",model,dataInput))  
  p4
}


```

##Combine FOI of all models
```{r fig.height=12,fig.width=10}

panel1 <- ggarrange(p1+theme(legend.position = "none"),
         p3 ,
         align = "h", # align x axis equaly
        widths =c(1/3,2/3),
         ncol = 2, nrow = 1)
panel1 
panel2 <- ggarrange(p2+theme(legend.position = "none"),
         p4 ,
         align = "h", # align x axis equaly
         widths =c(1/3,2/3),
         ncol = 2, nrow = 1)
panel2 

fig3 <- ggarrange(panel1,
         panel2,
         align = "v", # align y axis equaly
         widths =c(1/3,2/3),
         ncol = 1, nrow = 2)
fig3 

ggsave(filename=paste("./output/figures/Fig3.png"), plot = fig3, height = 8, width = 12)

```

