---
title: "FOI of DENV in HC&KH (Vietnam) ESTIMATION"
author: "Phuong Huynh Thi, collated by Maxine Tan"
date: "9/4/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

commit: original file:"Combined_FOI_Calculation_MLE.Rmd

```{r set working directory} 
rm(list=ls())
library(StanHeaders)
library(rstan)
library(dplyr)
library(tidyr)

util <- new.env()
source('./codes/stan_utility.R', local=util)
rstan_options(auto_write = TRUE) 
options(mc.cores = parallel::detectCores())

```

# indicate model type here!
## input site, data input, no. of steps for years
```{r data input & model selection, echo=FALSE, message=FALSE}
# Changeable 
model <- "cons" # cons, TV,SS, TVSS
groupAge <- 1 # Grouping Input data by group of 5
step_year <- 1 # non-TV models, input 0
site <- "HC" #KH, HC
dataInput <-"C1D1" # C1D1, C1F1, C1D3, C1F3
#for time-varying model, options are 1,2,3,4,5

if ( dataInput == "C1D1"){
    data <- read.csv("./data/PredictedIS_B23_567_pred.serotype_C1D1.csv")  
}
if ( dataInput == "C1D3"){
    data <- read.csv("./data/PredictedIS_B23_567_pred.serotype_C1D3.csv")  
}
if ( dataInput == "C1F1"){
    data <- read.csv("./data/PredictedIS_B23_567_pred.serotype_HomoAssigned_C1F1.csv")  
}
if ( dataInput == "C1F3"){
    data <- read.csv("./data/PredictedIS_B23_567_pred.serotype_HomoAssigned_C1F3.csv")  
}

data$YEAR <- as.factor(data$YEAR)
data$predictedIS<- ordered(data$predictedIS,levels=c("Secondary","Primary","Neg"))
data$pred.serotype<- as.factor(data$pred.serotype)

# Extract population data only!
pop<- data[which(!is.na(data$AGE_MIN)&is.na(data$PanbioUnit)),]#cross out acute and ELISA samples
pop$Site <- substr(pop$sampleID,1,2)

# Age grouping
if(groupAge == 1){
  ##Agegroup_ 1year
  pop$AgeGroup <-factor(as.factor(ceiling(pop$AGE_MIN)),labels=c("(1-2]","(2-3]","(3-4]","(4-5]","(5-6]","(6-7]","(7-8]","(8-9]","(9-10]","(10-11]","(11-12]","(12-13]","(13-14]","(14-15]","(15-16]","(16-17]","(17-18]","(18-19]","(19-20]","(20-21]","(21-22]","(22-23]","(23-24]","(24-25]","(25-26]","(26-27]","(27-28]","(28-29]","(29-30]"))# group as  1year 1 group, no individual is less than 1 year old 
}
if(groupAge == 2){
  pop$AgeGroup <-factor(as.factor(ceiling(pop$AGE_MIN/2)),labels=c("(0-2]","(2-4]","(4-6]","(6-8]","(8-10]","(10-12]","(12-14]","(14-16]","(16-18]","(18-20]","(20-22]","(22-24]","(24-26]","(26-28]","(28-30]"))
}
if(groupAge == 3){
  pop$AgeGroup <- ceiling(pop$AGE_MIN/3)
  pop$AgeGroup <- factor(
    pop$AgeGroup,
    labels = c("(0-3]","(3-6]","(6-9]","(9-12]","(12-15]","(15-18]",
               "(18-21]","(21-24]","(24-27]","(27-30]"))
}
if(groupAge == 5){
  pop$AgeGroup <- ceiling(pop$AGE_MIN/5)
  pop$AgeGroup <- factor(
    pop$AgeGroup,
    labels = c("(0-5]","(5-10]","(10-15]","(15-20]","(20-25]","(25-30]"))
}
             
```

# data filtering and preparation
```{r data preparation, echo=FALSE, message=FALSE}
if (site=="HC"){
    p_year=dplyr::filter(pop,Site=="HC")%>%group_by(AgeGroup,YEAR,Site)%>%dplyr::count(pred.serotype)%>%spread(pred.serotype,n)}
if(site == "KH"){
    p_year=dplyr::filter(pop,Site=="KH")%>%group_by(AgeGroup,YEAR,Site)%>%dplyr::count(pred.serotype)%>%spread(pred.serotype,n)}
if(site == "KH&HC"|site =="HC&KH"){
    p_year=dplyr::filter(pop)%>%group_by(AgeGroup,YEAR)%>%dplyr::count(pred.serotype)%>%spread(pred.serotype,n)
    p_year$Site <- "HC&KH" # add Site-> same no.columns-> later convenient
    #Rearrange by column index
    p_year <- p_year[,colnames(p_year)[c(1:2,9,3:8)]]
    }

# Sorting "YEAR" in chronological order
p_year<-p_year[order(p_year$YEAR),]

# p_year$total <- apply(p_year[,3:8],1,sum,na.rm=T)
p_year$Primary <-rowSums(p_year[,4:7],na.rm = T)
p_year$total <-rowSums(p_year[,4:9],na.rm = T)

#create function for substr age rather than put age in order, this is useful in case of missing data in a specific age: 
my_substr <- function(s){
  if (nchar(s) == 5){
    t <- substr(s, 4, 4)
  }else{
    if (nchar(s) == 6){
      t <- substr(s, 4, 5)
    }else{
      t <- substr(s, 5, 6)
    }
  }
  return(t)
}

# lower range
my_substr_lower <- function(s){
  if (nchar(s) == 5|nchar(s) == 6){
    t <- substr(s, 2, 2)
  }else{
    t <- substr(s, 2, 3)
  }
  return(t)
}

#
p_year$age<- apply(p_year[,1],1,my_substr)
p_year$age <- as.numeric(p_year$age)
p_year$age_lower<- apply(p_year[,1],1,my_substr_lower)
p_year$age_lower <- as.numeric(p_year$age_lower)
p_year$ageMean <- apply(p_year[,12:13],1,mean)

# Assign NA as 0 because stan does not support NA value:
for (idx in 4:9){
  idx.na <- which(is.na(p_year[[idx]]))
  p_year[[idx]][idx.na] <- 0
}

```

# data formatting for stan
```{r data format for stan, echo=FALSE,message=FALSE}

b = length(p_year$age)
n_y = 2017-2013+1+max(as.integer(p_year[which(p_year$YEAR==2013),]$age)) # number of years backward, time period that data is available ## KH: 36 -> 1982, HC: 35 -> 1983

# data input for constant FOI model
if (model == "cons") {
  datapp<- list(a = b,
              datap=c(p_year[1:b, 8],
                      p_year[1:b, 4],
                      p_year[1:b, 5],
                      p_year[1:b, 6],
                      p_year[1:b, 7],
                      p_year[1:b, 9]),
                      veca = as.integer(p_year$age),
                      veca_mean = as.integer(p_year$ageMean))
}

# data input for serotype-specific FOI model
if (model == "SS") {
  datapp<- list(a = b,
              datap=c(p_year[1:b, 8],
                      p_year[1:b, 4],
                      p_year[1:b, 5],
                      p_year[1:b, 6],
                      p_year[1:b, 7],
                      p_year[1:b, 9]),
                      veca=as.integer(p_year$age),
                      veca_mean = as.integer(p_year$ageMean))
}

#
if (model == "TV"|model == "TVSS"){
  
l_vecj = length(c(rep(1:ceiling(n_y/step_year), each =  step_year))) # ceiling: round up

datapp<- list(a = b,
              step_year = step_year,
              datap=c(p_year[1:b, 8],
                      p_year[1:b, 4],
                      p_year[1:b, 5],
                      p_year[1:b, 6],
                      p_year[1:b, 7],
                      p_year[1:b, 9]),
              vecj=as.integer(c(rep(1:ceiling(n_y/step_year), each =  step_year))),#for index of actual lambda
              l_vecj = length(c(rep(1:ceiling(n_y/step_year), each =  step_year))),# length of vecj for later use
              vecy=as.integer(as.character(p_year$YEAR)),
              veca=as.integer(p_year$age),
              veca_mean = as.integer(p_year$ageMean))

}

```

# Stan codes 
```{r}
if (model == "cons"&groupAge==1){
  FOI_Dengue <-"./codes/Stan_models/FOI_constant_MLE.stan"
}
if (model == "cons"&groupAge==5){
  FOI_Dengue <-"./codes/Stan_models/FOI_constant_MLE_GroupAge.stan"
}
# if (model == "SS"&groupAge==1){
#   FOI_Dengue <-"./codes/FoI/Stan/FOI_serotype_specific_MLE.stan"
# }
if (model == "SS"&groupAge==5){
  FOI_Dengue <-"./codes/Stan_models/FOI_serotype_specific_MLE_GroupAge.stan"
}
if (model == "TV"){
  FOI_Dengue <- "./codes/Stan_models/FOI_time varying_MLE.stan"
}
if (model == "TVSS"){
  FOI_Dengue <-"./codes/Stan_models/FOI_time varying_serotype specific_MLE.stan"
}

```

# run model and obtain posterior values
```{r result from model, echo=FALSE, message=FALSE,warning=FALSE, include=FALSE}
# you then run using this: From this output we can quickly assess model convergence by looking at the Rhat values for each parameter. When these are at or near 1, the chains have converged. There are many other diagnostics, but this is an important one for Stan.
set.seed(9)
fit<-stan(file = FOI_Dengue,
          data=datapp, iter=6000,
          chains= 4,
          cores = 4, # parallel::detectCores()
          control = list(adapt_delta=0.8, max_treedepth=10))# default
 
posterior <- rstan::extract(fit) # specify package rstan rather than tidyr

#this summarizes the parameters, gets mean,etc. of parameters and metrics of whether converged or not like Rhat and neff
foisummary <- summary(fit)
foisummary

tab <- data.frame(foisummary$summary)
# # saving fits
#trace previous result here: /home/phuong/pCloudDrive/PMA analysis results/FoI/RDS/FOI
if (model == "cons") {
  saveRDS(fit,paste("./output/RDS/FOI",model,"groupAge",groupAge,site,dataInput,".rds"))
} else if (model == "SS") {
  saveRDS(fit, paste("./output/RDS/FOI",model,"groupAge",groupAge,site,dataInput, ".rds"))
} else if (model == "TV") {
  saveRDS(fit, paste("./output/RDS/FOI",model,"groupAge",groupAge,"step_year",step_year,site,dataInput, ".rds"))
}else {
  saveRDS(fit,paste("./output/RDS/FOI",model,"groupAge",groupAge,"step_year",step_year,site,dataInput,".rds"))
}

#load saved fit
# fit <- readRDS(paste("./publication/output/RDS/FOI",model,"groupAge",groupAge,site,dataInput,".rds"))

# # plot to see whether estimated parameter is convergence or not: traceplot
# plottedRows <- 1 : nrow(posterior$lambda)
# plottedRows <- which(plottedRows %% 6 == 0)
# plot(posterior$lambda[plottedRows, 4],type="l")

```

